databases:
  shopCart:
    host: "postgresql"
    port: 5432
    user: "test"
    password: "secret"
    dbname: "shop_cart"

  # default:
  #   host: "postgresql"
  #   port: 5432
  #   user: "postgres"
  #   password: "9955"
  #   dbname: "postgres"

redis:
  host: "redis:6379"
  password: ""
  db: 0

proxyServer:
  # hostname is container name
  host: "proxy-server:8787"
  # host: "localhost:8787"