version: '3.8'

services:
  app:
    build: 
      context: .
    networks:
      - postgresql
      - redis
      - proxy-server
    depends_on:
      - "postgresql"

  postgresql:
    container_name: postgresql
    image: 'bitnami/postgresql:latest'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks: 
      - postgresql
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=shop_cart
      

networks:
  postgresql:
    name: postgresql
    driver: bridge
  proxy-server:
    name: proxy-server
    external: true
  redis:
    name: redis
    external: true
volumes:
  postgresql_data:
